version: "3.7"

services: 
  database:
    container_name: prisma-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=jeong
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=wjdwhdans
      - TZ='Asia/Seoul'
    ports: 
      - "3306:3306"

  redis:
    container_name: prisma-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'